### ISSUE TITLE
Default target list includes ARM

### ISSUE THREAD

**Issue by luismarques** [rv8-io/rv8-bench#1]
The documentation states:

```
To build the rv8 benchmarks for riscv32, riscv64, i386 and x86_64 run make in the rv8-bench directory:
```

But the default target list in the Makefile (`ALL_PROGS`) includes ARM32 and ARM64. I suggest:

1. Either update the Makefile or the documentation regarding the default targets
2. Add to the documentation the required steps to have the toolchain also built for the ARM targets

**Comment by larkmjc** [comment]
Hi Luis,

Thanks. I've amended README.md here: https://github.com/rv8-io/rv8-bench/commit/d61b32f9e04bf04ce6dea88607ab93497fad95af

The toolchain build scripts now virtualize the architecture build directories so there is no longer any need to remove the build subdirectory and stamps when building multiple architectures. Changes were made to speed up the build-time. The host independent build steps are now shared between the toolchain builds for multiple architectures (gmp, mpfr, mpc lib builds are reused). That said, it now requires 17.6GB free-disk space to build all 6 architectures. I should probably also add the disk space requirements to the README.

Michael
